name: 'Run compilation'
description: 'An action to compile gems with native extensions and test the resulting binary.'

inputs:
  working-directory:
    description: "The working directory of the gem"
    default: "."
    required: false
  release:
    description: "Push and release the gem with precompiled binaries."
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Checkout easy compile
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      with:
        path: "tmp"
        repository: "rails/cool-stuff-fun-time"
    - name: Install easy compile
      shell: bash
      run: "rake install"
      working-directory: "tmp"
    - name: Run easy compile
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: easy_compile
    - name: "Release"
      uses: Edouard-chin/release-gem@ec-working-dir
      if: ${{ inputs.release == 'true' }}
      with:
        working-directory: ${{ inputs.working-directory }}
        setup-trusted-publisher: true
        attestations: false
      env:
        RAKEOPT: "--require=${{ github.action_path }}/bundler_release.rb"
