name: 'Run compilation'
description: 'An action to compile gems with native extensions and test the resulting binary.'

inputs:
  working-directory:
    description: "The working directory of the gem"
    default: "."
    required: false
  step:
    description: "The step to run"
    required: true
  test-command:
    description: "The command to run the test suite. By default Easy Compile will run either `bundle exec rake test` or `bundle exec rake spec` depending on the test framework used."
    required: false
    default: "easy_compile test"

runs:
  using: "composite"
  steps:
    - name: Install easy compile # TODO this can be removed once this tool is pusblished on RubyGems
      shell: bash
      run: "rake install"
      working-directory: "${{ github.action_path }}"
    - name: "Setup Rake Compiler"
      if: "${{ inputs.step == 'compile' }}"
      uses: actions/github-script@v8
      with:
        script: |
          const url = new URL(`file:///${process.env.GITHUB_ACTION_PATH}/dist/index.js`);
          const { run } = await import(url.href)
          await run('${{ inputs.working-directory }}')
    - name: Package
      if: "${{ inputs.step == 'compile' }}"
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: easy_compile package
    - name: Upload artifacts
      if: "${{ inputs.step == 'compile' }}"
      uses: actions/upload-artifact@v4
      with:
        name: "stage-${{ runner.os }}-${{ runner.arch }}"
        path: |
          ${{ inputs.working-directory }}/tmp/**/*.so
          ${{ inputs.working-directory }}/tmp/**/*.bundle
          ${{ inputs.working-directory }}/pkg/*.gem
        if-no-files-found: error
        retention-days: 1
    - name: "Download compiled binaries"
      if: "${{ inputs.step == 'test_cross' }}"
      uses: actions/download-artifact@v5
      with:
        name: "stage-${{ runner.os }}-${{ runner.arch }}"
        path: "${{ inputs.working-directory }}"
    - name: "Copy staging binary to the libdir"
      if: "${{ inputs.step == 'test_cross' }}"
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: easy_compile copy_from_staging_to_lib
    - name: "Compile native"
      if: "${{ inputs.step == 'test_native' }}"
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: easy_compile compile
    - name: "Execute the tests"
      if: "${{ startsWith(inputs.step, 'test') }}"
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: ${{ inputs.test-command }}
    - name: "Download tarball for platform"
      if: "${{ inputs.step == 'install' }}"
      uses: actions/download-artifact@v5
      with:
        name: "stage-${{ runner.os }}-${{ runner.arch }}"
    - name: "Download all gems"
      if: "${{ inputs.step == 'release' }}"
      uses: actions/download-artifact@v5
      with:
        merge-multiple: true
    - name: "Install gems"
      if: "${{ inputs.step == 'install' }}"
      shell: bash
      run: gem install pkg/*.gem
    - name: "Configure RubyGems crendentials in preparation for publishing"
      if: "${{ inputs.step == 'release' }}"
      uses: rubygems/configure-rubygems-credentials@v1.0.0
    - name: "Push the gems to RubyGems"
      if: "${{ inputs.step == 'release' }}"
      shell: bash
      run: easy_compile release --glob "pkg/*"
    - name: "Waiting for RubyGems to fully index the new gems"
      if: "${{ inputs.step == 'release' }}"
      shell: bash
      run: gem exec rubygems-await pkg/*.gem
