name: 'Run compilation'
description: 'An action to compile gems with native extensions and test the resulting binary.'

inputs:
  working-directory:
    description: "The working directory of the gem"
    default: "."
    required: false
  step:
    description: "The step to run"
    required: true
  token:
    description: "TODO this is needed to install the Easy Compile gem from the GitHub repo. Can be removed "
    required: false
outputs:
  latest_supported_ruby_version:
    description: "The most recent ruby versions (from a list) this gem is compatible with."
    value: ${{ steps.get_versions.outputs.latest_supported_ruby_version }}
  runtime_version_for_compilation:
    description: "The ruby version used for compiling fat gems."
    value: ${{ steps.get_versions.outputs.runtime_version_for_compilation }}
  ruby_versions_for_testing:
    description: "An array of ruby versions selected from a list, compatible with the gem."
    value: ${{ steps.get_versions.outputs.ruby_versions_for_testing }}

runs:
  using: "composite"
  steps:
    - name: Checkout easy compile # TODO this can be removed once this tool is pusblished on RubyGems
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      with:
        path: "tmp"
        repository: "shopify-playground/edouard-playground"
        token: ${{ inputs.token }}
    - name: Install easy compile # TODO this can be removed once this tool is pusblished on RubyGems
      shell: bash
      run: "rake install --local"
      working-directory: "tmp"
    - name: "Outputs the ruby versions needed for compilation"
      if: "${{ inputs.step == 'get_versions' }}"
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      id: get_versions
      run: easy_compile get_versions
    - name: "Setup Ruby"
      if: "${{ inputs.step == 'compile' }}"
      uses: "ruby/setup-ruby@v1"
      with:
        ruby-version: "3.4.7"
    - name: "Setup Rake Compiler"
      if: "${{ inputs.step == 'compile' }}"
      uses: actions/github-script@v8
      with:
        script: |
          const url = new URL(`file:///${process.env.GITHUB_ACTION_PATH}/dist/index.js`);
          const { run } = await import(url.href)
          await run('${{ inputs.working-directory }}')
    - name: Package
      if: "${{ inputs.step == 'compile' }}"
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: easy_compile package
    - name: Upload artifacts
      if: "${{ inputs.step == 'compile' }}"
      uses: actions/upload-artifact@v4
      with:
        name: "stage-${{ runner.os }}-${{ runner.arch }}"
        path: |
          ${{ inputs.working-directory }}/tmp/**/*.so
          ${{ inputs.working-directory }}/tmp/**/*.bundle
          ${{ inputs.working-directory }}/pkg/*.gem
        if-no-files-found: error
        retention-days: 1
    - name: "Download compiled binaries"
      if: "${{ inputs.step == 'test_cross' }}"
      uses: actions/download-artifact@v5
      with:
        name: "stage-${{ runner.os }}-${{ runner.arch }}"
        path: "${{ inputs.working-directory }}"
    - name: "Copy staging binary to the libdir"
      if: "${{ inputs.step == 'test_cross' }}"
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: easy_compile copy_from_staging_to_lib
    - name: "Compile native"
      if: "${{ inputs.step == 'test_native' }}"
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: easy_compile compile
    - name: "Execute the tests"
      if: "${{ startsWith(inputs.step, 'test') }}"
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: bundle exec rake test # TODO This should be configurable
    - name: "Download tarball for platform"
      if: "${{ inputs.step == 'install' }}"
      uses: actions/download-artifact@v5
      with:
        name: "stage-${{ runner.os }}-${{ runner.arch }}"
    - name: "Download all gems"
      if: "${{ inputs.step == 'release' }}"
      uses: actions/download-artifact@v5
      with:
        merge-multiple: true
    - name: "Install gems"
      if: "${{ inputs.step == 'install' }}"
      shell: bash
      run: gem install pkg/*.gem
    - name: "Configure RubyGems crendentials in preparation for publishing"
      if: "${{ inputs.step == 'release' }}"
      uses: rubygems/configure-rubygems-credentials@v1.0.0
    - name: "Push the gems to RubyGems"
      if: "${{ inputs.step == 'release' }}"
      shell: bash
      run: easy_compile release --glob "pkg/*"
    - name: "Waiting for RubyGems to fully index the new gems"
      if: "${{ inputs.step == 'release' }}"
      shell: bash
      run: gem exec rubygems-await pkg/*.gem
