name: 'Run compilation'
description: 'An action to compile gems with native extensions and test the resulting binary.'

inputs:
  working-directory:
    description: "The working directory of the gem"
    default: "."
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout easy compile
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      with:
        path: "tmp"
        repository: "shopify-playground/edouard-playground"
    - name: Install easy compile
      shell: bash
      run: "rake install"
      working-directory: "tmp"
    - name: Compile and test
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: easy_compile
    - name: "Setup Rake Compiler"
      uses: actions/github-script@v8
      with:
        script: |
          const url = new URL(`file:///${process.env.GITHUB_ACTION_PATH}/dist/index.js`);
          const { run } = await import(url.href)
          await run('${{ inputs.working-directory }}')
    - name: Package gems with precompiled binaries
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: easy_compile clobber && easy_compile package
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: "package-${{ runner.os }}-${{ runner.arch }}"
        path: "${{ inputs.working-directory }}/pkg/*.gem"
        if-no-files-found: error
        overwrite: true
        retention-days: 1
